// Generated by Flexc++ V0.98.00 on Thu, 02 Aug 2012 10:24:42 -0500

#ifndef KismetScanner_H_INCLUDED_
#define KismetScanner_H_INCLUDED_

// $insert baseclass_h
#include "KismetScannerbase.h"

#include "KismetParserbase.h"

// $insert namespace-open
namespace KISMET
{

// $insert classHead
class KismetScanner: public KismetScannerBase
{
    public:
        explicit KismetScanner(std::istream &in = std::cin,
                                std::ostream &out = std::cout);

        KismetScanner(std::string const &infile, std::string const &outfile);

        // $insert lexFunctionDecl
        int lex();

    private:
        int lex__();
        int executeAction__(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must
                            // be exec'ed before the patternmatching starts
};

// $insert scannerConstructors
inline KismetScanner::KismetScanner(std::istream &in, std::ostream &out)
:
    KismetScannerBase(in, out)
{}

inline KismetScanner::KismetScanner(std::string const &infile, std::string const &outfile)
:
    KismetScannerBase(infile, outfile)
{}

// $insert inlineLexFunction
inline int KismetScanner::lex()
{
    return lex__();
}

inline void KismetScanner::preCode()
{
    // optionally replace by your own code
}

inline void KismetScanner::print()
{
    print__();
}

// $insert namespace-close
}

#endif // KismetScanner_H_INCLUDED_

